### ISSUE TITLE
Automatic fill mode

### ISSUE THREAD

**Issue by Pukkahq** [RolandRust/HaniMandlWroom#6]
If you have a jar fill weight of 500g. in automatic mode if it fills to 498g you remove the jar and put it down again it will automatically open the honey gate again. if the jar fill is 501g it does nothing.

**Comment by RolandRust** [comment]
which version do you use? With version W.0.2 I have never seen that the servo opens again if you place a glass on it without pressing the start button.

**Comment by Pukkahq** [comment]
W.0.2 

We are in automatic mode. 
Place a jar, press start. 
If its under filled and you pick it up and put it back on the scales it will open the valve.

**Comment by RolandRust** [comment]
I have now tested it with version W.0.2 and don't see the phenomenon. As you can see in the video, I have to press the start button so that the squeeze valve opens when a glass that has already been started is placed on the scale.
 https://youtu.be/VfxytLiSxO4

**Comment by RolandRust** [comment]
I made now other experiments with exactly  498g, but I can not see the Issue that the honey gate open automatic after remove the Jar and put it again on the scale. Can you send my a Video in a case when this happens? when its a bug I have to know what you are doing. As long I can not reproduce this case it is not possible to solve this problem.

**Comment by Pukkahq** [comment]
I will test again with the new DEV code and report back

**Comment by Pukkahq** [comment]
I managed to get this to fail, but did not recored it. 

The machine is in full automatic mode, press start, fill jar to 495g. lift jar and put back down slowly. start will appear on the display and the gate will open.

**Comment by RolandRust** [comment]
I have now made several attempts to get the HM into this condition. Unfortunately I haven't been able to do it yet. I think you have to proceed a little systematically to find the error (there must be one)
In order for Start to appear on the display after picking up the glass and putting it back on, the following conditions must be met:
if (auto_aktiv == 1 && abs(gewicht) <= glastoleranz && servo_aktiv == 0 and turntable_ok == true and stop_wait_befor_fill == 0 and stop_button_close_dp == 0)
- auto_aktiv --> always 1 if in the full automatic mode
- abs(gewicht) --> Weight that is on the scale
- glastoleranz --> Your saved Value in the EEprom from the Setup - Automatic- Jar toleranze
- servo_aktiv --> will be set to 0 if you remove the jar from the scale
- turntable_ok --> always 1 if you do not use the turntable (new in W.0.03)
- stop_wait_befor_fill  --> always 0 if you do not use the turntable (new in W.0.03)
- stop_button_close_dp -->  always 0 if you do not use your recommend feature to fill something in the jar after the tare (new in W.0.03)
So we can ignore a lot of variables --> auto_aktiv, servo_aktiv, turntable_ok, stop_wait_befor_fill, stop_button_close_dp.
Now we have two left:  abs(gewicht) and glastoleranz
The Value glastoleranz is saved in the EEprom and has a Value between 0 and 99.
The Value abs(gewicht)  is the weight from the scale minus the saved value in the EEprom for the jar weight.
Even if you have 99g in the glass tolerance, we are still a long way away (ok 99 doesn't really make sense). There would be a maximum of 198g capacity at which the servo would be opened (a bit much but not the problem here, as we have well over 400g). 
Fazit: Could be a SW Bug during using weak HW. Could try to evaluate the variable gewicht during a average value . makes the HM slower.

**Comment by RolandRust** [comment]
there must be a value to get in the weight that's  wrong. can you send me a picture from your XH711 that you are using?
